# Generated by Django 5.2.7 on 2025-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.CharField()),
                ('optional', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
