# Generated by Django 5.2.7 on 2025-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('page_url', models.URLField()),
                ('browser', models.CharField(max_length=200)),
                ('user_agent', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('severity', models.IntegerField(default=0)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
