# Generated by Django 5.2.7 on 2025-11-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bugreporter_delete_samplemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreporter',
            name='browser',
        ),
    ]
